theme = "tokyomodded"
# theme = "monokai_pro_spectrum"

[editor]
line-number = "relative"
scroll-lines = 7
completion-timeout = 5
completion-replace = true
clipboard-provider = "wayland"
bufferline = "always"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center= ["version-control"]
right = ["diagnostics", "workspace-diagnostics", "selections", "register", "position", "total-line-numbers", "file-encoding"]

[editor.auto-save]
after-delay.enable = false

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"

[editor.file-picker]
hidden = false

[keys.normal]
"F1" = ":set whitespace.render all"
"F2" = ":set whitespace.render none"
